# Docker compose to spin up the demo controller
#
version: '3.5'

networks:
    agency-network:
        external: true

services:
    demo-controller:
        env_file:
            - .env
        build:
            context: ../../controller
            dockerfile: Dockerfile
        command: npm run start:debug
        image: demo-controller
        container_name: demo-controller
        working_dir: /www
        ports:
            - "3014:3014"
        volumes:
            - ../../controller/:/www
            - ./:/www/implementations/demo
        networks:
            - agency-network
        tty: true
