# Spin up the dependencies for demo-controller circle ci tests
#
version: '3.5'

networks:
    agency-network:
      name: agency-network
      driver: bridge
      ipam:
        driver: default
        config:
          -
            subnet: 10.0.0.0/24

services:
    demo-controller:
        image: kivaprotocol/aries-controller:latest
        container_name: demo-controller
        working_dir: /www
        ports:
            - "3014:3014"
        networks:
            - agency-network
        tty: true
        environment:
            - NODE_ENV=LOCAL
            - MULTI_AGENT=false
            - MULTI_CONTROLLER=true
            - PORT=3014
            - SELF_URL=http://demo-controller:3014
            - ADMIN_API_KEY=adminApiKey
