# Spin up the demo controller using production image
#
version: '3.5'

networks:
    agency-network:
        external: true

services:
    demo-controller:
        build:
            context: .
            dockerfile: Dockerfile.production
        image: demo-controller
        container_name: demo-controller
        working_dir: /www
        ports:
            - "3014:3014"
        networks:
            - agency-network
        tty: true
        depends_on: 
            - indy-pool
        environment:
            - NODE_ENV=LOCAL
            - MULTI_AGENT=true
            - MULTI_CONTROLLER=true
            - PORT=3014
            - SELF_URL=http://demo-controller:3014
            - ADMIN_API_KEY=adminApiKey
