# Docker compose to spin up the demo controller
#
version: '3.5'

networks:
    agency-network:
        external: true

services:
    demo-controller:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:debug
        image: demo-controller
        container_name: demo-controller
        working_dir: /www
        ports:
            - "3014:3014"
        volumes:
            - ./:/www
            # For dev purposes this simulates npm-link, since symbolic links on the mac won't work in the docker container
            # - ../../../aries-controller/dist:/www/node_modules/aries-controller
        networks:
            - agency-network
        tty: true
