version: 2.1

jobs:
  integration-test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup shell environment
          command: |
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Setup node
          command: |
              nvm install v14.15.1
              node -v
              nvm alias default v14.15.1
      - run:
          name: Setup demo
          command: |
            docker pull bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
      - run:
          name: Start docker compose and wait for readiness
          command: |
            docker-compose -f docker-compose.yml up -d
            sleep 30
            docker-compose -f docker-compose.yml logs
      - run:
          name: Setup integration tests
          command: |
            npm install
      - run:
          name: Running demo integration tests
          command: |
            if ! npm run test:integration ; then
              echo "Tests failed. Server logs:";
              docker-compose -f docker-compose.yml logs;
              exit 1;
            fi
workflows:
  build-test-deploy:
    jobs:
      - integration-test:
          requires:
            - build-and-test
          filters: # run for all branches AND tags
            tags:
              only: /.*/
      - docker/publish:
          requires:
              - build-and-test
              - integration-test
          filters: # only run for semver tagged versions
              tags:
                  only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
              branches:
                  ignore: /.*/
          update-description: true
          dockerfile: Dockerfile.production
          image: kivaprotocol/demo-controller
          tag: << pipeline.git.tag >>,latest

orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@1.3.0
